spring.application.name=devops-demo
spring.datasource.url=jdbc:postgresql://localhost:5432/doc-db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true